Add new functions to handle exit codes easier

diff --git a/git-ftp b/git-ftp
--- a/git-ftp
+++ b/git-ftp
@@ -298,10 +298,54 @@ get_keychain_password () {
 }
 
 # Checks if last command was successful
+#
+# $1 - error message
+# $2 - error code to produce
+#
 check_exit_status() {
-	if [ $? -ne 0 ]; then
-		print_error_and_die "$1, exiting..." "$2"
+	check_exit_status_not_equals $? 0 "$1" "$2"
+}
+
+# Checks if exit status equals a given value. If false sends exit command.
+#
+# $1 - status code to check
+# $2 - code to test against
+# $3 - error message
+# $4 - error code to produce
+#
+check_exit_status_equals() {
+	if [ $1 -eq $2 ]; then
+		print_error_and_die "$3, exiting..." "$4"
 	fi
+}
+
+# Checks if exit status not equals a given value
+#
+# $1 - status code to check
+# $2 - code to test against
+# $3 - error message
+# $4 - error code to produce
+#
+check_exit_status_not_equals() {
+	if [ $1 -ne $2 ]; then
+		print_error_and_die "$3, exiting..." "$4"
+	fi
+}
+
+# Checks if a given curl exit code was successful and if not exits with a nice error message (in some cases)
+#
+# $1 - exit code to check
+# $2 - message: a custom message that is put in front of the error message
+# $3 - error code: code to exit with if $1 is bad
+#
+check_curl_exit_status() {
+	case $1 in
+		0) ;;
+		9) print_error_and_die "$2 Access to resource denied. This usually means that the file or directory does not exist. Wrong path? exiting..." "$3" ;;
+		67) print_error_and_die "$2 Can't access remote '$REMOTE_BASE_URL_DISPLAY'. Failed to log in. Correct user and password? exiting..." "$3" ;;
+		78) print_error_and_die "$2 The resource does not exist. exiting..." "$3" ;;
+		*) print_error_and_die "$2 Can't access remote '$REMOTE_BASE_URL_DISPLAY'. Network down? Wrong URL? exiting..." "$3" ;;
+	esac
 }
 
 get_config() {
